
package itp120mod2ANSWERS17_18;

import java.text.NumberFormat;

// import java.text.NumberFormat;

public class Payroll	{
	
	//class variables
	private String name;
	private int idNumber;
	private double hourlyPayRate;
	private double hoursWorked;
	
	// no argument constructor
	public Payroll()
	{
		
	}

	// full constructor - autogenerated
     public Payroll(String name, int idNumber, double hourlyPayRate,
			double hoursWorked) {
		this.name = name;
		this.idNumber = idNumber;
		this.hourlyPayRate = hourlyPayRate;
		this.hoursWorked = hoursWorked;
	}

     // return gross pay 
     public double grossPay(){
    	 return hourlyPayRate * hoursWorked;
     }
     
    // toString 
	public String toString() {
		NumberFormat nf = NumberFormat.getCurrencyInstance();
		return name + " with and id of " + idNumber + " worked " +
					hoursWorked + " at an hourly rate of " + nf.format(hourlyPayRate) + 
					" and a gross pay of " + nf.format(grossPay());
	}

	// getters and setters - autogenerated
	public String getName() {
		return name;
	}



	public void setName(String name) {
		this.name = name;
	}



	public int getIdNumber() {
		return idNumber;
	}



	public void setIdNumber(int idNumber) {
		this.idNumber = idNumber;
	}



	public double getHourlyPayRate() {
		return hourlyPayRate;
	}



	public void setHourlyPayRate(double hourlyPayRate) {
		this.hourlyPayRate = hourlyPayRate;
	}



	public double getHoursWorked() {
		return hoursWorked;
	}



	public void setHoursWorked(double hoursWorked) {
		this.hoursWorked = hoursWorked;
	}

}
