
package itp120mod4.Ex3.classes;

public class SmartRobot 
{
	private String robotName;  
	private int robotIQ;

	//constructors
	public SmartRobot() // no argument constructor
	{
	}
	
	public SmartRobot (String n, int i) //constructor with parameters
	{
		robotName = n;
		robotIQ = i;
	}
	
	//toString() method
	public String toString() 
	{
		return "The smartest robot is " + robotName + " with an IQ of " + robotIQ + ".";
	}

		
	//getters and setters generated by Eclipse
	public int getRobotIQ() {
		return robotIQ;
	}

	public void setRobotIQ(int robotIQ) {
		this.robotIQ = robotIQ;
	}

	public String getRobotName() {
		return robotName;
	}

	public void setRobotName(String robotName) {
		this.robotName = robotName;
	}
	
}
